import { Surah } from "./types";

export const quranSurahs: Surah[] = [
  { number: 1, name: "Al-Fatihah", arabic: "الفاتحة", totalVerses: 7, revelation: "Makkiyah" },
  { number: 2, name: "Al-Baqarah", arabic: "البقرة", totalVerses: 286, revelation: "Madaniyah" },
  { number: 3, name: "Ali 'Imran", arabic: "آل عمران", totalVerses: 200, revelation: "Madaniyah" },
  { number: 4, name: "An-Nisa'", arabic: "النساء", totalVerses: 176, revelation: "Madaniyah" },
  { number: 5, name: "Al-Ma'idah", arabic: "المائدة", totalVerses: 120, revelation: "Madaniyah" },
  { number: 6, name: "Al-An'am", arabic: "الأنعام", totalVerses: 165, revelation: "Makkiyah" },
  { number: 7, name: "Al-A'raf", arabic: "الأعراف", totalVerses: 206, revelation: "Makkiyah" },
  { number: 8, name: "Al-Anfal", arabic: "الأنفال", totalVerses: 75, revelation: "Madaniyah" },
  { number: 9, name: "At-Taubah", arabic: "التوبة", totalVerses: 129, revelation: "Madaniyah" },
  { number: 10, name: "Yunus", arabic: "يونس", totalVerses: 109, revelation: "Makkiyah" },
  { number: 11, name: "Hud", arabic: "هود", totalVerses: 123, revelation: "Makkiyah" },
  { number: 12, name: "Yusuf", arabic: "يوسف", totalVerses: 111, revelation: "Makkiyah" },
  { number: 13, name: "Ar-Ra'd", arabic: "الرعد", totalVerses: 43, revelation: "Madaniyah" },
  { number: 14, name: "Ibrahim", arabic: "إبراهيم", totalVerses: 52, revelation: "Makkiyah" },
  { number: 15, name: "Al-Hijr", arabic: "الحجر", totalVerses: 99, revelation: "Makkiyah" },
  { number: 16, name: "An-Nahl", arabic: "النحل", totalVerses: 128, revelation: "Makkiyah" },
  { number: 17, name: "Al-Isra'", arabic: "الإسراء", totalVerses: 111, revelation: "Makkiyah" },
  { number: 18, name: "Al-Kahf", arabic: "الكهف", totalVerses: 110, revelation: "Makkiyah" },
  { number: 19, name: "Maryam", arabic: "مريم", totalVerses: 98, revelation: "Makkiyah" },
  { number: 20, name: "Taha", arabic: "طه", totalVerses: 135, revelation: "Makkiyah" },
  { number: 21, name: "Al-Anbiya'", arabic: "الأنبياء", totalVerses: 112, revelation: "Makkiyah" },
  { number: 22, name: "Al-Hajj", arabic: "الحج", totalVerses: 78, revelation: "Madaniyah" },
  { number: 23, name: "Al-Mu'minun", arabic: "المؤمنون", totalVerses: 118, revelation: "Makkiyah" },
  { number: 24, name: "An-Nur", arabic: "النور", totalVerses: 64, revelation: "Madaniyah" },
  { number: 25, name: "Al-Furqan", arabic: "الفرقان", totalVerses: 77, revelation: "Makkiyah" },
  { number: 26, name: "Asy-Syu'ara'", arabic: "الشعراء", totalVerses: 227, revelation: "Makkiyah" },
  { number: 27, name: "An-Naml", arabic: "النمل", totalVerses: 93, revelation: "Makkiyah" },
  { number: 28, name: "Al-Qashash", arabic: "القصص", totalVerses: 88, revelation: "Makkiyah" },
  { number: 29, name: "Al-'Ankabut", arabic: "العنكبوت", totalVerses: 69, revelation: "Makkiyah" },
  { number: 30, name: "Ar-Rum", arabic: "الروم", totalVerses: 60, revelation: "Makkiyah" },
  { number: 31, name: "Luqman", arabic: "لقمان", totalVerses: 34, revelation: "Makkiyah" },
  { number: 32, name: "As-Sajdah", arabic: "السجدة", totalVerses: 30, revelation: "Makkiyah" },
  { number: 33, name: "Al-Ahzab", arabic: "الأحزاب", totalVerses: 73, revelation: "Madaniyah" },
  { number: 34, name: "Saba'", arabic: "سبأ", totalVerses: 54, revelation: "Makkiyah" },
  { number: 35, name: "Fathir", arabic: "فاطر", totalVerses: 45, revelation: "Makkiyah" },
  { number: 36, name: "Yasin", arabic: "يس", totalVerses: 83, revelation: "Makkiyah" },
  { number: 37, name: "As-Saffat", arabic: "الصافات", totalVerses: 182, revelation: "Makkiyah" },
  { number: 38, name: "Sad", arabic: "ص", totalVerses: 88, revelation: "Makkiyah" },
  { number: 39, name: "Az-Zumar", arabic: "الزمر", totalVerses: 75, revelation: "Makkiyah" },
  { number: 40, name: "Ghafir", arabic: "غافر", totalVerses: 85, revelation: "Makkiyah" },
  { number: 41, name: "Fushshilat", arabic: "فصلت", totalVerses: 54, revelation: "Makkiyah" },
  { number: 42, name: "Asy-Syura", arabic: "الشورى", totalVerses: 53, revelation: "Makkiyah" },
  { number: 43, name: "Az-Zukhruf", arabic: "الزخرف", totalVerses: 89, revelation: "Makkiyah" },
  { number: 44, name: "Ad-Dukhan", arabic: "الدخان", totalVerses: 59, revelation: "Makkiyah" },
  { number: 45, name: "Al-Jatsiyah", arabic: "الجاثية", totalVerses: 37, revelation: "Makkiyah" },
  { number: 46, name: "Al-Ahqaf", arabic: "الأحقاف", totalVerses: 35, revelation: "Makkiyah" },
  { number: 47, name: "Muhammad", arabic: "محمد", totalVerses: 38, revelation: "Madaniyah" },
  { number: 48, name: "Al-Fath", arabic: "الفتح", totalVerses: 29, revelation: "Madaniyah" },
  { number: 49, name: "Al-Hujurat", arabic: "الحجرات", totalVerses: 18, revelation: "Madaniyah" },
  { number: 50, name: "Qaf", arabic: "ق", totalVerses: 45, revelation: "Makkiyah" },
  { number: 51, name: "Adz-Dzariyat", arabic: "الذاريات", totalVerses: 60, revelation: "Makkiyah" },
  { number: 52, name: "At-Tur", arabic: "الطور", totalVerses: 49, revelation: "Makkiyah" },
  { number: 53, name: "An-Najm", arabic: "النجم", totalVerses: 62, revelation: "Makkiyah" },
  { number: 54, name: "Al-Qamar", arabic: "القمر", totalVerses: 55, revelation: "Makkiyah" },
  { number: 55, name: "Ar-Rahman", arabic: "الرحمن", totalVerses: 78, revelation: "Madaniyah" },
  { number: 56, name: "Al-Waqi'ah", arabic: "الواقعة", totalVerses: 96, revelation: "Makkiyah" },
  { number: 57, name: "Al-Hadid", arabic: "الحديد", totalVerses: 29, revelation: "Madaniyah" },
  { number: 58, name: "Al-Mujadilah", arabic: "المجادلة", totalVerses: 22, revelation: "Madaniyah" },
  { number: 59, name: "Al-Hasyr", arabic: "الحشر", totalVerses: 24, revelation: "Madaniyah" },
  { number: 60, name: "Al-Mumtahanah", arabic: "الممتحنة", totalVerses: 13, revelation: "Madaniyah" },
  { number: 61, name: "As-Saff", arabic: "الصف", totalVerses: 14, revelation: "Madaniyah" },
  { number: 62, name: "Al-Jumu'ah", arabic: "الجمعة", totalVerses: 11, revelation: "Madaniyah" },
  { number: 63, name: "Al-Munafiqun", arabic: "المنافقون", totalVerses: 11, revelation: "Madaniyah" },
  { number: 64, name: "At-Taghabun", arabic: "التغابن", totalVerses: 18, revelation: "Madaniyah" },
  { number: 65, name: "At-Talaq", arabic: "الطلاق", totalVerses: 12, revelation: "Madaniyah" },
  { number: 66, name: "At-Tahrim", arabic: "التحريم", totalVerses: 12, revelation: "Madaniyah" },
  { number: 67, name: "Al-Mulk", arabic: "الملك", totalVerses: 30, revelation: "Makkiyah" },
  { number: 68, name: "Al-Qalam", arabic: "القلم", totalVerses: 52, revelation: "Makkiyah" },
  { number: 69, name: "Al-Haqqah", arabic: "الحاقة", totalVerses: 52, revelation: "Makkiyah" },
  { number: 70, name: "Al-Ma'arij", arabic: "المعارج", totalVerses: 44, revelation: "Makkiyah" },
  { number: 71, name: "Nuh", arabic: "نوح", totalVerses: 28, revelation: "Makkiyah" },
  { number: 72, name: "Al-Jinn", arabic: "الجن", totalVerses: 28, revelation: "Makkiyah" },
  { number: 73, name: "Al-Muzzammil", arabic: "المزمل", totalVerses: 20, revelation: "Makkiyah" },
  { number: 74, name: "Al-Muddatstsir", arabic: "المدثر", totalVerses: 56, revelation: "Makkiyah" },
  { number: 75, name: "Al-Qiyamah", arabic: "القيامة", totalVerses: 40, revelation: "Makkiyah" },
  { number: 76, name: "Al-Insan", arabic: "الإنسان", totalVerses: 31, revelation: "Madaniyah" },
  { number: 77, name: "Al-Mursalat", arabic: "المرسلات", totalVerses: 50, revelation: "Makkiyah" },
  { number: 78, name: "An-Naba'", arabic: "النبأ", totalVerses: 40, revelation: "Makkiyah" },
  { number: 79, name: "An-Nazi'at", arabic: "النازعات", totalVerses: 46, revelation: "Makkiyah" },
  { number: 80, name: "'Abasa", arabic: "عبس", totalVerses: 42, revelation: "Makkiyah" },
  { number: 81, name: "At-Takwir", arabic: "التكوير", totalVerses: 29, revelation: "Makkiyah" },
  { number: 82, name: "Al-Infitar", arabic: "الإنفطار", totalVerses: 19, revelation: "Makkiyah" },
  { number: 83, name: "Al-Muthaffifin", arabic: "المطففين", totalVerses: 36, revelation: "Makkiyah" },
  { number: 84, name: "Al-Insyiqaq", arabic: "الانشقاق", totalVerses: 25, revelation: "Makkiyah" },
  { number: 85, name: "Al-Buruj", arabic: "البروج", totalVerses: 22, revelation: "Makkiyah" },
  { number: 86, name: "At-Thariq", arabic: "الطارق", totalVerses: 17, revelation: "Makkiyah" },
  { number: 87, name: "Al-A'la", arabic: "الأعلى", totalVerses: 19, revelation: "Makkiyah" },
  { number: 88, name: "Al-Ghasyiyah", arabic: "الغاشية", totalVerses: 26, revelation: "Makkiyah" },
  { number: 89, name: "Al-Fajr", arabic: "الفجر", totalVerses: 30, revelation: "Makkiyah" },
  { number: 90, name: "Al-Balad", arabic: "البلد", totalVerses: 20, revelation: "Makkiyah" },
  { number: 91, name: "Asy-Syams", arabic: "الشمس", totalVerses: 15, revelation: "Makkiyah" },
  { number: 92, name: "Al-Lail", arabic: "الليل", totalVerses: 21, revelation: "Makkiyah" },
  { number: 93, name: "Ad-Duha", arabic: "الضحى", totalVerses: 11, revelation: "Makkiyah" },
  { number: 94, name: "Asy-Syarh", arabic: "الشرح", totalVerses: 8, revelation: "Makkiyah" },
  { number: 95, name: "At-Tin", arabic: "التين", totalVerses: 8, revelation: "Makkiyah" },
  { number: 96, name: "Al-'Alaq", arabic: "العلق", totalVerses: 19, revelation: "Makkiyah" },
  { number: 97, name: "Al-Qadr", arabic: "القدر", totalVerses: 5, revelation: "Makkiyah" },
  { number: 98, name: "Al-Bayyinah", arabic: "البينة", totalVerses: 8, revelation: "Madaniyah" },
  { number: 99, name: "Az-Zalzalah", arabic: "الزلزلة", totalVerses: 8, revelation: "Madaniyah" },
  { number: 100, name: "Al-'Adiyat", arabic: "العاديات", totalVerses: 11, revelation: "Makkiyah" },
  { number: 101, name: "Al-Qari'ah", arabic: "القارعة", totalVerses: 11, revelation: "Makkiyah" },
  { number: 102, name: "At-Takatsur", arabic: "التكاثر", totalVerses: 8, revelation: "Makkiyah" },
  { number: 103, name: "Al-'Asr", arabic: "العصر", totalVerses: 3, revelation: "Makkiyah" },
  { number: 104, name: "Al-Humazah", arabic: "الهمزة", totalVerses: 9, revelation: "Makkiyah" },
  { number: 105, name: "Al-Fil", arabic: "الفيل", totalVerses: 5, revelation: "Makkiyah" },
  { number: 106, name: "Quraisy", arabic: "قريش", totalVerses: 4, revelation: "Makkiyah" },
  { number: 107, name: "Al-Ma'un", arabic: "الماعون", totalVerses: 7, revelation: "Makkiyah" },
  { number: 108, name: "Al-Kautsar", arabic: "الكوثر", totalVerses: 3, revelation: "Makkiyah" },
  { number: 109, name: "Al-Kafirun", arabic: "الكافرون", totalVerses: 6, revelation: "Makkiyah" },
  { number: 110, name: "An-Nashr", arabic: "النصر", totalVerses: 3, revelation: "Madaniyah" },
  { number: 111, name: "Al-Lahab", arabic: "اللهب", totalVerses: 5, revelation: "Makkiyah" },
  { number: 112, name: "Al-Ikhlas", arabic: "الإخلاص", totalVerses: 4, revelation: "Makkiyah" },
  { number: 113, name: "Al-Falaq", arabic: "الفلق", totalVerses: 5, revelation: "Makkiyah" },
  { number: 114, name: "An-Nas", arabic: "الناس", totalVerses: 6, revelation: "Makkiyah" }
];

export const juzStarts = [
  { juz: 1, surah: 1, verse: 1 },
  { juz: 2, surah: 2, verse: 142 },
  { juz: 3, surah: 2, verse: 253 },
  { juz: 4, surah: 3, verse: 93 },
  { juz: 5, surah: 4, verse: 24 },
  { juz: 6, surah: 4, verse: 148 },
  { juz: 7, surah: 5, verse: 82 },
  { juz: 8, surah: 6, verse: 111 },
  { juz: 9, surah: 7, verse: 88 },
  { juz: 10, surah: 8, verse: 41 },
  { juz: 11, surah: 9, verse: 93 },
  { juz: 12, surah: 11, verse: 6 },
  { juz: 13, surah: 12, verse: 53 },
  { juz: 14, surah: 15, verse: 1 },
  { juz: 15, surah: 17, verse: 1 },
  { juz: 16, surah: 18, verse: 75 },
  { juz: 17, surah: 21, verse: 1 },
  { juz: 18, surah: 23, verse: 1 },
  { juz: 19, surah: 25, verse: 21 },
  { juz: 20, surah: 27, verse: 56 },
  { juz: 21, surah: 29, verse: 46 },
  { juz: 22, surah: 33, verse: 31 },
  { juz: 23, surah: 36, verse: 28 },
  { juz: 24, surah: 39, verse: 32 },
  { juz: 25, surah: 41, verse: 47 },
  { juz: 26, surah: 46, verse: 1 },
  { juz: 27, surah: 51, verse: 31 },
  { juz: 28, surah: 58, verse: 1 },
  { juz: 29, surah: 67, verse: 1 },
  { juz: 30, surah: 78, verse: 1 }
];

export function getJuzNumber(surah: number, verse: number): number {
  for (let i = juzStarts.length - 1; i >= 0; i--) {
    const boundary = juzStarts[i];
    if (surah > boundary.surah) {
      return boundary.juz;
    } else if (surah === boundary.surah && verse >= boundary.verse) {
      return boundary.juz;
    }
  }
  return 1;
}

